# Generated by Django 6.0.3 on 2026-04-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_vk_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vk_user_id',
            field=models.BigIntegerField(blank=True, help_text='Числовой id как в vk.com/id… — при входе через ВК подставляется автоматически.', null=True, unique=True, verbose_name='ID ВКонтакте'),
        ),
    ]
