# Generated by Django 5.x migration

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_vk_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='ClanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'На рассмотрении'),
                            ('approved', 'Принята'),
                            ('rejected', 'Отклонена'),
                        ],
                        default='pending',
                        max_length=20,
                        verbose_name='Статус',
                    ),
                ),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='Никнейм')),
                ('uid', models.CharField(blank=True, max_length=50, verbose_name='UID')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('vk_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID ВКонтакте')),
                ('clan_points_snapshot', models.IntegerField(default=0, verbose_name='ОК на момент заявки')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='clan_applications',
                        to='users.user',
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Заявка в клан',
                'verbose_name_plural': 'Заявки в клан',
                'ordering': ['-created_at'],
            },
        ),
    ]
